#!/bin/sh
# Usage: wmlock [-b]
#       -b: suspend if on battery
#       -h: help

print_help() {
    cat - <<EOF
Usage: wmlock [-b]
    -b: suspend if on battery
    -h: display help
EOF
}

lock() {
    rnd="$$"
    locker="/usr/local/share/pixmaps/wmlock/locker.png"

    sname="/tmp/screenshot.$rnd.png"
    lname="/tmp/lockscreen.$rnd.png"

    scrot "$sname"
    size="$(identify -format '%wx%h' "$sname")"
    mogrify -scale 3% -scale $size -fill black -colorize 70% "$sname"
    if [ -e "$locker" ]; then
        convert "$sname" "$locker" -gravity center -composite "$lname"
    else
        mv "$sname" "$lname"
    fi

    rm "$sname"
    i3lock -nefi "$lname" -c 000000
    rm "$lname"
}

while getopts ":bh" opt; do
    case "$opt" in
        b)
            bat_check=true
            ;;
        h)
            print_help
            exit 0
            ;;
        *)
            print_help >&2
            exit 1
            ;;
    esac
done

if ps -aux | grep -v grep | grep -q i3lock; then
    exit 0
fi

if [ "$bat_check" = "true" ] && acpi -b | grep -q 'Discharging'; then
    systemctl suspend
else
    lock
fi
